version: '3.8'

services:
  app:
    build: .
    container_name: accountmanagement
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/accountmanagement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_LIQUIBASE_ENABLED=true
    networks:
      - accountmanagement-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: accountmanagement-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=accountmanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - accountmanagement-network
    restart: unless-stopped

networks:
  accountmanagement-network:
    driver: bridge

volumes:
  postgres-data: